server: 
  port: 8081
spring: 
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
       enabled: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  
             
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.mvc.format.date-time: yyyy-MM-dd HH:mm:ss